### ISSUE TITLE
Allow either direct tuple of species and coordinates or temporary file to create Molecule object. 

### ISSUE THREAD

**Issue by khuddzu** [openforcefield/openff-toolkit#1137]
I am trying to implement your software in my project. Currently our data is in h5 format, and we have tensors of species and coordinates with dimensions [M, Na] and [M, Na, 3] respectively, where M is number of conformers and Na is number of atoms in conformation. 
If species and coordinates are s and c, then I have tried to create the Molecule object using (s, c) to see if this would work. It would be nice if it would, so you don't actually have to have a file you just need your data. 
I have also tried creating a temporary file with the data I have using the following code: 

for k,v in ds.items():                                                         # ds is my dataset
    species = ds[k]['species']
    coordinates = ds[k]['coordinates']
    for s, c in zip(species, coordinates):                                      #iterating through each conformation
        s = s.unsqueeze(0)
        c = c.unsqueeze(0)
        temp = tempfile.NamedTemporaryFile(mode='r+', suffix='.xyz')            #Create temp file 
        tensor_to_xyz(temp.name, (s, c), truncate_output_file=True)             #make xyz 
        mol = next(pybel.readfile('xyz', temp.name))                            #create mol object
        temp.close()                                                            #close temp file
        mol_raw = mol.write(format='mol')                                       #create mol file object
        mol = Molecule.from_file(mol_raw, file_format="XYZ")

I have also tried the above code but instead of the mol file object, I then created an rdkit Mol object and then tried to create your Molecule object, and this didn't work. 
Also, it should be noted that it is still reading a xyz file so the error I am getting is Bad File Input. with the temp file. this error might be solved with allowing XYZ as a file format for the inout of the Molecule object, but I am not sure. 

The most convenient option for me. however, is to allow for direct input of species and coordinates. 

Thank you. Please let me know if I can help in any way to resolve this issue.

**Comment by mattwthompson** [comment]
Hi Kate,

Thanks for raising this issue. It looks like one of the issues here is that you're trying to create a `Molecule` from only an XYZ file. That's not supported because coordinates and elements alone aren't enough information to define the chemistry (bonds, bond orders, stereochemistry, formal charge) needed for SMIRNOFF-style chemical perception. The same is true for generating a `Molecule` from only atomic coordinates. So a different intermediate file would be needed, ideally something like SDF or a cheminformatics representation like SMILES/InCHI. I see you're using Open Babel as an intermediate here, but it looks like that's only storing the same information as is in the XYZ file? Maybe there's information in `species` - is this just a name for bookkeeping, or is it something that carries more information?

**Comment by khuddzu** [comment]
Ah I see. 
Yes we only have xyz information. Species is just a list of atomic numbers and coordinates does not contain any other information that position in space. 
From this I can create a SDF and I believe SMILEs as well, but I havent done it. However, with the SDF the MOL file information would only have the XYZ information, the values for bond information would be zero. Is this okay? How does that effect the calculations?

**Comment by mattwthompson** [comment]
SMILES records would definitely be preferred, SDF files with bond information scrapped out would probably not be read properly. However, I'm not sure SMILES can be reliably generated from coordinates and atoms alone; I think there are some project out there that attempt to do so but it's scientifically too hard a problem for there to be a robust solution.

Some other suggestions can be found [here](https://open-forcefield-toolkit.readthedocs.io/en/0.10.1/faq.html#what-do-you-recommend-as-a-starting-point), though if your data sources are truly just elements and positions you're going to keep running into the [fundamental problem](https://open-forcefield-toolkit.readthedocs.io/en/0.10.1/faq.html#what-kinds-of-input-files-can-i-apply-smirnoff-parameters-to) and not be able to use SMIRNOFF-style force fields. (I think this is not true for ANI and other machine learning tools, though I'm not no so familiar with them myself). So the only hope here might be going farther upstream to how the h5 format data was generated - maybe there was more chemical information in an earlier step.

**Comment by khuddzu** [comment]
Okay. Thank you. I will speak with Adrian to see what he thinks and take a look at these resources. Does it change anything if we are only interested in obtaining AMBER Antechamber charge values. no other parameters (which I have never used before and am still learning about)?

**Comment by mattwthompson** [comment]
In that case, calling `antechamber` directly might be a more direct path to your solution, though I'm not sure if it will also need more information than coordinates and atomic positions. The OpenFF Toolkit wraps an `antechamber` call to generate partial charges, which is [here](https://github.com/openforcefield/openff-toolkit/blob/a4c184d09f78ef9d2911631126dc322d61ddae28/openff/toolkit/utils/ambertools_wrapper.py#L216-L286) and could be adapted to your use case. You'll probably want to pass in `molecule.xyz` or something instead of an SDF file like the toolkit does.

**Comment by khuddzu** [comment]
I think I looked at this in your documentation... so assign partial charges doesn't require a Molecule object? You can use xyz? Or are you saying, that would be easy to modify to allow for xyz?

**Comment by j-wags** [comment]
Hi @khuddzu,

Thanks for writing in. I agree with everything @mattwthompson and @lilyminium said so far. 

I know of some workflows that people use to guess connectivity from XYZ, though as Matt said, these will occasionally make mistakes:

* [xyz2mol](https://github.com/jensengroup/xyz2mol/)
* MDAnalysis has a new connectivity guesser - [here's some code to try it out](https://github.com/openforcefield/openff-toolkit/issues/1126#issuecomment-969712195) (and I see @lilyminium posted a similar snippet while I typed this)
* openbabel may also be able to guess connectivity, though I haven't used it in a while so this could be wrong

These solutions kinda represent the rickety rope bridge between the world of "3D molecules" (physics) and "graph molecules/kekule structures" (cheminformatics). Unfortunately, there's a chicken-and-egg problem when we talk about molecules, where on one hand they're definitely a kekule structure, and on another they're also definitely a 3D arrangement of atoms, but there's no clear mapping between the two. Whenever possible, I try to plan studies so they'll avoid having to do a transition between these two worlds, since some unknown fraction of my dataset ends up getting mangled in the process. 

> I think I looked at this in your documentation... so assign partial charges doesn't require a Molecule object? You can use xyz? Or are you saying, that would be easy to modify to allow for xyz?

For now, anything that will become an OpenFF Toolkit `Molecule` basically needs "graph molecule/kekule structure" info - that is, every atom should know at least its element and formal charge, and every bond should know its bond order. It would be quite difficult to make the OpenFF toolkit accommodate a molecule representation that doesn't have that information.

@mattwthompson is suggesting that your workflow could circumvent the OpenFF toolkit altogether, and instead feed the `xyz` molecules directly into `antechamber`. My understanding of QM jobs is that, at a minimum, they need to know elements and positions for all particles, as well as the total charge of the molecule (analogous to the total number of electrons). The suitability of this approach depends on the overall goal of the work - If you just want AM1 charges, then (elements+positions+total charge) could be all you need. On the other hand, if the goal is to use a method like AM1BCC, then the connectivity would need to be known, since the application of BCCs are based on the "graph" of the molecules (since, for example, an sp2 carbon may be treated differently than an sp3 carbon).

> we are only interested in obtaining AMBER Antechamber charge values. no other parameters

Maybe a little more detail here could help us guide you. Antechamber can run several methods to provide charges. Some of them require graph info (such as "gasteiger" and "AM1BCC"), but others can run with just elements+positions+total charge (like "RESP" and maybe "AM1"). Which method do you plan to run for your study?

**Comment by mattwthompson** [comment]
(I had this written up before Lily's and Jeff's replies - which are more useful, but I'll post this anyway).

> so assign partial charges doesn't require a Molecule object?

It does - your reading is correct.

My suggestion here is that you could rip out the code and run `antechamber` directly instead of going through the toolkit. This would involve more or less copying the code linked above and modifying it to run as a standalone function. Wrapping it yourself would allow you to do it inside of a Python loop without going back and forth between the shell.


```python3
def get_antechamber_charges(xyz_file: str) -> np.ndarray:
    # Call antechamber
    subprocess.check_output(["antechamber", "-i", ...])
    # Write out just charges
    subprocess.check_output(["antechamber", ..., "-cf", "charges.txt"])
    # Read charges from charges.txt into some sort of array
    charges = ...
    return charges
```

You'd then be able to call this function inside a loop like you have above. This would bypass the need for a full cheminformatics representation, since it does not act on our `Molecule` objects, but I suspect Antechamber will still at some point need to know bonds. A PDB file is probably close enough - @lilyminium's code seems like it's on the path toward some sort of solution. I'd definitely recommend getting this working by hand with a single file/molecule first.

**Comment by khuddzu** [comment]
Wow thank you guys so much for all of your help! I am going to try out some of your suggestions and let you know what the winner was!

**Comment by khuddzu** [comment]
Hi, so I was able to use babel to get obtain gasteiger partial charges. However, say I was looking at NH4+, the software seems to know the total charge on the molecule is +1. But if I compute gasteiger partial charges the value sum of these charges are 0. If I change to another charge type. like QTPie for example, the sum in +1. This says to me there is a problem with the gasteiger partition. Have you all run into this problem?

**Comment by j-wags** [comment]
I haven't run into this before, and we may be of limited use for obabel/antechamber questions. That said, this post doesn't provide enough information for us to know exactly what you tried, so we can't suggest alternatives. Could you provide a reproducing example of the problem? GitHub can nicely format code blocks if you put them inside triple-backticked strings (```), so if you could do that for the ammonium input file and the command(s) you tried, that would be really helpful.

**Comment by khuddzu** [comment]
yes of course. rather than obabel file converter I will show the pybel interface. The charges are the same. 

Let's start with Gasteiger charges:
ammonium.mol2:
```
@<TRIPOS>MOLECULE
ammonium.xyz
 5 4 0 0 0
SMALL
GASTEIGER

@<TRIPOS>ATOM
      1 N          -1.5575    1.1684   -0.1589 N.4     1  LIG1        0.3770
      2 H          -0.5344    1.1364    0.0484 H       1  LIG1       -0.0942
      3 H          -1.7080    1.0618   -1.1869 H       1  LIG1       -0.0942
      4 H          -1.9482    2.0841    0.1570 H       1  LIG1       -0.0942
      5 H          -2.0395    0.3915    0.3459 H       1  LIG1       -0.0942
@<TRIPOS>BOND
     1     3     1    1
     2     1     2    1
     3     1     4    1
     4     1     5    1
```
I then used pybel to see what information it has from this file:
```
INPUT:
mol = next(pybel.readfile('mol2', '{}ammonium.mol2'.format(wkdir)))    
mol.charge                             ##Prints charge of the total structure. So pybel reads this structure as having a +1 charge

>> 1
```
Now let's look at the formal charges on the atoms:

```
INPUT:
fcs = []
for atom in mol:
    print(atom)                                                                 ##Prints atoms atomic number and its coordinates
    print("Formal Charge for atom:", atom.formalcharge) ##Prints the formal charge of that atom
    print()
    fcs.append(atom.formalcharge)
print("Sum of atomic charges:", np.sum(fcs))                ##Do these values give me a sum that equals the total charge above? 

>> Atom: 7 (-1.56 1.17 -0.16)        ##N
Formal Charge for atom: 1

Atom: 1 (-0.53 1.14 0.05)          ##H
Formal Charge for atom: 0

Atom: 1 (-1.71 1.06 -1.19)        ##H
Formal Charge for atom: 0

Atom: 1 (-1.95 2.08 0.16)         ##H
Formal Charge for atom: 0

Atom: 1 (-2.04 0.39 0.35)              ##H
Formal Charge for atom: 0

Sum of atomic charges: 1             ##Yes this value equals the total charge from above
```

Now let's look at the partial charges using Gasteiger charges

```
INPUT:
pcs = []
for atom in mol:
    print(atom)
    print('Gasteiger partial charge for atom:',  atom.partialcharge)      ##Getting partial charges from file, whihc here are gasteiger
    print()
    pcs.append(atom.partialcharge)
print("Sum of atomic Charges:", np.sum(pcs))  ##Does the sum of these values give the total charge from above? 

>>Atom: 7 (-1.56 1.17 -0.16)                                                        ##N
Gasteiger partial charge for atom: 0.377

Atom: 1 (-0.53 1.14 0.05)                                                            ##H
Gasteiger partial charge for atom: -0.0942

Atom: 1 (-1.71 1.06 -1.19)                                                          ##H
Gasteiger partial charge for atom: -0.0942

Atom: 1 (-1.95 2.08 0.16)                                                         ##H
Gasteiger partial charge for atom: -0.0942

Atom: 1 (-2.04 0.39 0.35)                                                         ##H
Gasteiger partial charge for atom: -0.0942

Sum of atomic Charges: 0.00019999999999997797              ## No they do not give the correct total charge
```


I also did the above, but with a file that contained QTPIE charges. They did provide the right sum, however in my work I am uninterested in using QTPIE. 
Because of this, and because of the right total charge and formal charges that pybel provides, I do not think this is a babel issue. I think this is a gasteiger issue. However, this is my first time using them so I am unsure. 
I was wondering, since you all compute gasteiger charges using your software, if you have run into this same issue? Where they do not sum to the proper total charge.
Let me know if there is any more information you need. 

Thank you so much for spending so much time with me on this. I understand if this is not something you can help with. I just thought I would give it a shot. 

Best, 
Kate

**Comment by lilyminium** [comment]
This does not happen when OpenFF calls antechamber or OpenEye, so I'd put it down to an openbabel issue. 

```
>>> from openff.toolkit.topology import Molecule
>>> from openff.toolkit.utils import AmberToolsToolkitWrapper, OpenEyeToolkitWrapper
>>> mol = Molecule.from_smiles("[NH4+]")
>>> mol.assign_partial_charges("gasteiger", toolkit_registry=AmberToolsToolkitWrapper())
>>> mol.partial_charges.sum()
Quantity(value=1.0, unit=elementary charge)
>>> mol.partial_charges
Quantity(value=array([0.223772, 0.194057, 0.194057, 0.194057, 0.194057]), unit=elementary charge)
>>> mol.assign_partial_charges("gasteiger", toolkit_registry=OpenEyeToolkitWrapper())
>>> mol.partial_charges.sum()
Quantity(value=1.0, unit=elementary charge)
>>> mol.partial_charges
Quantity(value=array([0.20986462, 0.19753385, 0.19753385, 0.19753385, 0.19753385]), unit=elementary charge)
```

How are you calculating the charges? This ten year old mailing list issue has a similar problem: https://openbabel-discuss.narkive.com/WMqtiX2E/open-babel-calculating-partial-charges-with-openbabel-of-a-positively-charged-molecule

**Comment by lilyminium** [comment]
Can confirm that the fix suggested in the thread worked for me:

```bash
(pybel)  ~  echo "[NH4+]" > nh4.smi
(pybel)  ~  obabel nh4.smi -O nh4.mol2 --gen3d
1 molecule converted
(pybel)  ~  grep UNL nh4.mol2 | awk 'BEGIN{s=0}{s+=$9}END{print s}'
0.9999
(pybel)  ~  obabel nh4.smi -O nh4_g.mol2 --gen3d --partialcharge gasteiger
1 molecule converted
(pybel)  ~  grep UNL nh4_g.mol2 | awk 'BEGIN{s=0}{s+=$9}END{print s}'
0.0002
```

Files:

nh4.mol2
```
@<TRIPOS>MOLECULE
*****
 5 4 0 0 0
SMALL
GASTEIGER

@<TRIPOS>ATOM
      1 N           0.9130    0.0358   -0.0339 N.4     1  UNL1        0.2099
      2 H           1.9398    0.0358   -0.0339 H       1  UNL1        0.1975
      3 H           0.5708   -0.5357   -0.8153 H       1  UNL1        0.1975
      4 H           0.5708    0.9982   -0.1382 H       1  UNL1        0.1975
      5 H           0.5708   -0.3552    0.8516 H       1  UNL1        0.1975
@<TRIPOS>UNITY_ATOM_ATTR
1 1
charge 1
@<TRIPOS>BOND
     1     1     2    1
     2     1     3    1
     3     1     4    1
     4     1     5    1
```

nh4_g.mol2:
```
@<TRIPOS>MOLECULE
*****
 5 4 0 0 0
SMALL
GASTEIGER

@<TRIPOS>ATOM
      1 N           1.0456    0.0865    0.0207 N.4     1  UNL1        0.3770
      2 H           2.0724    0.0865    0.0207 H       1  UNL1       -0.0942
      3 H           0.7034   -0.7071    0.5750 H       1  UNL1       -0.0942
      4 H           0.7034    0.0034   -0.9437 H       1  UNL1       -0.0942
      5 H           0.7034    0.9634    0.4310 H       1  UNL1       -0.0942
@<TRIPOS>UNITY_ATOM_ATTR
1 1
charge 1
@<TRIPOS>BOND
     1     1     2    1
     2     1     3    1
     3     1     4    1
     4     1     5    1
```

**Comment by khuddzu** [comment]
Ah this was very insightful. The issue I am having here is the same issue I was having using your software. I am going from a xyz file, and there is not enough information provided. Thank you so much. 
I imagine I will keep running into this error. But I will try some more of your other previous recommendations.

**Comment by lilyminium** [comment]
Using gasteiger charges will always be a touchy problem without a known molecular graph, I'm afraid. :/ It might be worthwhile building in a step in your workflow where you validate the inferred graphs instead of jumping straight to charge calculation; at least this will separate graph problems vs charge problems and make debugging easier. Alternatively, you could consider some of the charge methods Jeff suggested that do not require knowing the connectivity of the molecule, such as RESP or AM1.

**Comment by khuddzu** [comment]
Hey sorry to bother you guys again. I am still trying to get around the "known Molecular graph issue". I have successfully made mol objects in a sdf file, using rdkit. And if the conformer gives and error in this process, I just scrap it. I can successfully make these Molecule objects! 

However, I am not getting another error (I will share my code and error message). I am not sure what this means. Is this something I am doing incorrect, or is still a Molecular graph issue? 


`for sdf in test_sdfs:
    f_path = test_sdf_dir + sdf
    suppl = Chem.SDMolSupplier(f_path)
    for m in suppl:
        if m is not None:
            mol = Molecule.from_rdkit(m)
            mol.assign_partial_charges(partial_charge_method='am1bcc', toolkit_registry=AmberToolsToolkitWrapper())
#             print(mol.partial_charges)`

Error message: 
`
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_DIVIDE_BY_ZERO IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
/home/khuddzu/anaconda3/envs/ani/bin/wrapped_progs/antechamber: Fatal Error!
Unable to find sqm charges in file (sqm.out).
Verify the filename and the file contents.
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
/tmp/ipykernel_19423/3314129526.py in <module>
      5         if m is not None:
      6             mol = Molecule.from_rdkit(m)
----> 7             mol.assign_partial_charges(partial_charge_method='am1bcc', toolkit_registry=AmberToolsToolkitWrapper())
      8 #             print(mol.partial_charges)
      9 

~/anaconda3/envs/ani/lib/python3.8/site-packages/openff/toolkit/topology/molecule.py in assign_partial_charges(self, partial_charge_method, strict_n_conformers, use_conformers, toolkit_registry, normalize_partial_charges)
   3476         elif isinstance(toolkit_registry, ToolkitWrapper):
   3477             toolkit = toolkit_registry
-> 3478             toolkit.assign_partial_charges(
   3479                 self,
   3480                 partial_charge_method=partial_charge_method,

~/anaconda3/envs/ani/lib/python3.8/site-packages/openff/toolkit/utils/ambertools_wrapper.py in assign_partial_charges(self, molecule, partial_charge_method, use_conformers, strict_n_conformers, normalize_partial_charges, _cls)
    226                 # TODO: Add error handling if antechamber chokes
    227                 short_charge_method = charge_method["antechamber_keyword"]
--> 228                 subprocess.check_output(
    229                     [
    230                         "antechamber",

~/anaconda3/envs/ani/lib/python3.8/subprocess.py in check_output(timeout, *popenargs, **kwargs)
    413         kwargs['input'] = empty
    414 
--> 415     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    416                **kwargs).stdout
    417 

~/anaconda3/envs/ani/lib/python3.8/subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    514         retcode = process.poll()
    515         if check and retcode:
--> 516             raise CalledProcessError(retcode, process.args,
    517                                      output=stdout, stderr=stderr)
    518     return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['antechamber', '-i', 'molecule.sdf', '-fi', 'sdf', '-o', 'charged.mol2', '-fo', 'mol2', '-pf', 'yes', '-dr', 'n', '-c', 'bcc', '-nc', '0.0']' returned non-zero exit status 1.`

**Comment by j-wags** [comment]
Hm, I've never seen anything like this before. Could you figure out which molecule from the SDF is causing the error and upload it here?

**Comment by khuddzu** [comment]
Here is the mol block
```
/tmp/tmpp5xy6cpx.xyz
     RDKit          3D

 24 24  0  0  1  0  0  0  0  0999 V2000
    3.5136   -2.2471    0.2383 C   0  0  2  0  0  0  0  0  0  0  0  0
    2.0245   -1.8830    0.3398 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.3876   -1.2333    1.0099 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.3106    0.1659    0.4437 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.2883    1.0381    0.8277 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.2412    0.5972   -0.5034 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.2017    2.3138    0.2801 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.1564    1.8736   -1.0528 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.1367    2.7348   -0.6613 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.5406    1.6189   -0.2683 C   0  0  2  0  0  0  0  0  0  0  0  0
   -3.5731    2.6799    0.1565 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.5298    0.4012    0.6835 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.3727   -0.7652    0.2096 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.7596   -1.9419   -0.2232 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.7680   -0.6837    0.1765 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.5167   -3.0176   -0.6800 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.5254   -1.7565   -0.2807 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.9042   -2.9266   -0.7107 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.9732   -2.3545   -1.1295 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2544    2.2990   -0.4553 N   0  0  0  0  0  0  0  0  0  0  0  0
    1.3321   -1.6298   -0.6078 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.5039   -1.8635    1.5914 O   0  0  0  0  0  0  0  0  0  0  0  0
   -4.5816    2.4284    0.7695 O   0  0  0  0  0  0  0  0  0  0  0  0
   -3.2645    3.9151   -0.2410 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  1  3  1  0
  2 22  1  0
  4  5  2  0
  4  3  1  0
  6  4  1  0
  7  5  1  0
  8  9  1  0
  8  6  2  0
  9  7  2  0
 10 11  1  0
 10 12  1  0
 11 23  2  0
 13 12  1  0
 14 13  2  0
 15 13  1  0
 16 14  1  0
 17 15  2  0
 18 16  2  0
 18 17  1  0
  1 19  1  6
 10 20  1  1
 21  2  2  0
 24 11  1  0
M  END
```

**Comment by j-wags** [comment]
Ah, the problem there seems to be that there are two molecules in that one SDF entry. If I split it into the two separate molecules they seem to make it through the workflow just fine.

**Comment by khuddzu** [comment]
Sorry. Back again to bother you. I am asking a simple question, but I am providing way too much information for it. But none the less.....
From this code:
```
count = 0
ecount=0
for k,v in ds.items():
    species = ds[k]['species']
    coordinates = ds[k]['coordinates']
    for s, c in zip(species, coordinates):                                      #iterating through each conformation
        s = s.unsqueeze(0)
        c = c.unsqueeze(0)
        try:
            rdmol = mf.create_RdMOL_object(s, c, canonicalize=True, rm_H=False)
            mol = Molecule.from_rdkit(rdmol)
            print(mol)
            mol.assign_partial_charges(partial_charge_method='am1bcc', toolkit_registry=AmberToolsToolkitWrapper())
            print(mol.partial_charges)
            count+=1       
        except:
            print('error')
            ecount+=1
            continue
            
print(ecount)
print(count)
```
I am getting this partial output:
```
Molecule with name '/tmp/tmp937rkp26.xyz' and SMILES '[Cl][Cl]'
[0. 0.] e
Molecule with name '/tmp/tmppq7impvj.xyz' and SMILES '[F][Cl]'
[-0.102  0.102] e
```
Great. but I wanted to make sure that the 'e' doesn't signify some kind of error, or that I am doing something wrong, or missing some key word that would be helpful in this situation before I move on. 

Thaqnk you guys so much for helping! You have been tremendous.

**Comment by j-wags** [comment]
Hi @khuddzu,

The `e` in that case shows that you have `Quantity`, in units of `elementary_charge`. A `Quantity` is a special python class (in this case, from [OpenMM](http://docs.openmm.org/7.7.0/api-python/generated/openmm.unit.quantity.Quantity.html)) that has both a value (`[-0.102, 0.102]`) AND a unit (`e`, or elementary charge`). 

By using `Quantities`, we ensure that we don't misinterpret a value, just like doing unit cancellation in a chemistry math problem. So if someone was doing math that needed charges in Coulombs, then the `Quantity` object would know that it's in `elementary_charge`, and could raise an error or automatically do the conversion to ensure that the user gets the right answer.

**Comment by khuddzu** [comment]
ah perfect. thank you so much!
