### ISSUE TITLE
Atom mapping between original molecules & final system through parmed

### ISSUE THREAD

**Issue by pschmidtke** [openforcefield/openff-toolkit#1141]
**Is your feature request related to a problem? Please describe.**
I'm trying to address the following use case: 
I'm building a system inspired by this post here (BRD4 example): [BRD example](https://notebook.community/open-forcefield-group/openforcefield/examples/using_smirnoff_with_amber_protein_forcefield/BRD4_inhibitor_benchmark)

I'd like to know how to match atom indices (one particular atom on the ligand molecule from the complex structure (saved as pdb for example)) to the initial molecule read in from an sd file and or to an rdkit molecule (so Molecule("input.sdf").to_rdkit()). 

Is such a mapping even possible?

Cheers.

Peter

**Describe the solution you'd like**

From a fully parametrized openmm system I'd like to have an easy way to circle back to the original small molecule, possibly through atom tags / index list kept as metadata? Not sure how this is handled right now. Also as things go through parmed (in the example) this might be an issue. 

**Describe alternatives you've considered**
I'm considering filtering the ligand out, write out as mol2, read in back with rdkit (failing, because tripos atom types not supported). So considering to write as mol2 & transform with openbabel, run contrained embedded minimization and match the position of the atom that has been selected like that (that's super cumbersome, but should be tehcnically feasible).
**Additional context**

**Comment by lilyminium** [comment]
Is there only one ligand of that structure in the complex? I can think of a convoluted zero initial knowledge process involving

- Read complex PDB with MDAnalysis
- Select ligand atomgroup, with SMILES or residue name. Atomgroups have absolute index attributes 
- convert ligand atomgroup to RDKit molecule to OpenFF molecule. All caveats of converting PDB to molecular graph apply. Atom order is preserved. 
- use Molecule.chemical_environment_matches to narrow down relative index of atom of interest
- use this to index the ligand MDAnalysis atomgroup to get the absolute index of the atom

**Comment by pschmidtke** [comment]
Thanks for the suggestion. The situation I have is that I have a webviewer (showing the content of the prepared pdb file). Corresponding to that I run an openFF / openmm based minimization streaming the positions during the minimization back to the viewer. Once done, I have thus my complex.pdb shown with new positions in the webviewer. 

i want the user now to be able to modify the compound in the binding site by clicking for instance on a proton and change that to a CH3 (for example) -> then reparametrize, run minimization (within the flexible binding site) and stream things to the viewer. 

The issue is, how can I get an rdkit molecule back from the minimized openmm system? Or am I missing something obvious?

Cheers

**Comment by j-wags** [comment]
Hi @pschmidtke,

I'm working on providing a code block that should do what you want. The big two API points that should make it possible are `Topology.from_openmm` and `Molecule.are_isomorphic`. 

```python
# (somehow get just the ligand from the parameterized system as an OpenMM topology called "omm_top")
orig_ligand = Molecule.from_file('ligand.sdf')
top = Topology.from_openmm(omm_top, unique_molecules=[orig_lig])
_, atom_map = Molecule.are_isomorphic(orig_ligand, top.reference_molecules[0], return_atom_map=True)
```

I'll post a more complete solution once I have put the whole example together.

**Comment by pschmidtke** [comment]
Hi @j-wags,

thanks a lot. In case you need the code I'm using: 
https://github.com/Discngine/3d-editor/blob/main/data/sample.py

It's the match between the ligand.sdf read molecule and the final complex.pdb (or underlying complex_structure allowing mapping syntax like :L8A@H7 ;) 

Thanks again.

Peter

**Comment by j-wags** [comment]
Ok, I may have gotten as far as the major APIs can take me here. There are two parts to this atom map question:

1. Solving the LOCAL index map problem: "if the ligand in the ParmEd structure is rearranged compared to the SDF structure, how do we map between them?"
2. Solving the GLOBAL index map problem: "atom 5 in the ParmEd ligand is atom X in the whole ParmEd structure?"

I've solved problem 1 in the code below. Problem 2 should be solvable as well, but it's more ParmEd-centric and I have a meeting in a few minutes, so I may leave that unanswered!

```python
complex_structure = receptor_structure + ligand_structure

from openff.toolkit.topology import Topology, Molecule

orig_lig = Molecule.from_file('ligand.sdf')
omm_lig_top = complex_structure.split()[1][0].topology
off_lig_top = Topology.from_openmm(omm_lig_top, unique_molecules=[orig_lig])

iso, atom_map = Molecule.are_isomorphic(orig_lig, 
                                        off_lig_top.topology_molecules[0], 
                                        return_atom_map=True)
print(atom_map)
```
> {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15, 16: 16, 17: 17, 18: 18, 19: 19, 20: 20, 21: 21, 22: 22, 23: 23, 24: 24, 25: 25}

In this particular case, the atom map is unexciting, since I also made the system using `ligand.sdf`. But in the case that some part of the workflow rearranged it, this should be a good solution to problem 1. 

The solution to problem 2 will be something along the lines of tracking the indices through that `complex_structure.split()` command, but I couldn't find a simple solution on that front, so some more manual bookkeeping may be needed.

**Comment by j-wags** [comment]
Two other things - 
* I noticed the link in the original post was to a website called `notebook.community` and had an outdated version of our example. It's a nice looking website, but wonder if there's some way to make it stay up to date
* The code sample in discngine uses the old namespace (`from openforcefield...`) instead of the new namespace (`from openff.toolkit...`), so you may need to switch that to get the code from my last post to run

**Comment by pschmidtke** [comment]
Yes, I already switched to the new namespace locally. Just didn't push yet, but it doesn't really change the workflow, just module names & rearrangements ;) 

Thanks for the insights. I already had a look into the parmed mapping (especially with the masking syntax - which is relevant for the pdb & residue name / atom name case), but I'd have to extract some if the internal atom mappings there I guess. 

thanks again for the help!!
