### ISSUE TITLE
Topology object properties should point to reference_molecule

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-toolkit#1147]
**Describe the bug**

https://github.com/openforcefield/openff-toolkit/blob/9a9289cef2e7114be92201abfab318959c8bca33/openff/toolkit/topology/topology.py#L435-L444

`TopologyMolecule.molecule` doesn't exist; this should probably be `TopologyMolecule.reference_molecule`.  The `molecule` property is present on a number of classes in that file.

**To Reproduce**

```python
>>> mol = Molecule.from_smiles("CC")
>>> bond = list(mol.to_topology().topology_bonds)[0]
>>> bond.molecule
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lily/pydev/toolkit/openff/toolkit/topology/topology.py", line 607, in molecule
    return self._topology_molecule.molecule
AttributeError: 'TopologyMolecule' object has no attribute 'molecule'
```

**Output**

**Computing environment (please complete the following information):**
 - Operating system
 - Output of running `conda list` 

**Additional context**

Probably relevant to #951

**Comment by mattwthompson** [comment]
This seems to be a missed line in the [code coverage](https://app.codecov.io/gh/openforcefield/openff-toolkit/blob/9a9289cef2e7114be92201abfab318959c8bca33/openff/toolkit/topology/topology.py), too. Screenshot since it's not so easy to share at a specific line number:

![image](https://user-images.githubusercontent.com/7935382/145099593-70e2b655-d117-4b0a-a7e7-a7354b4c0c82.png)
