### ISSUE TITLE
Unable to override create_openmm_system default charge assignment with forcefield

### ISSUE THREAD

**Issue by arepstein** [openforcefield/openff-toolkit#1175]
**Describe the bug**
`create_openmm_system` hangs for large molecules even when charges are assigned and included through the forcefield as described in [issue 1126](https://github.com/openforcefield/openff-toolkit/issues/1126)

**To Reproduce**
```
smile = "O=C(OC(C)(C)CC/1=O)C1=C(O)/CCCCCCCC/C(NCCN(CCN)CCN)=C2C(OC(C)(C)CC/2=O)=O"
off_mol = Molecule.from_smiles(smile)

# Assign partial charges from a list-like object
charges = [0]*len(off_mol.atoms)
off_mol.partial_charges = np.asarray(charges) * unit.elementary_charge

library_charge_type = LibraryChargeHandler.LibraryChargeType.from_molecule(off_mol)
forcefield = ForceField("openff_unconstrained-2.0.0.offxml")
forcefield["LibraryCharges"].add_parameter(parameter=library_charge_type)

topology = off_mol.to_topology()
system = forcefield.create_openmm_system(topology)
```

`create_openmm_system()`'does not hang when adding partial charges directly, as in
`system = forcefield.create_openmm_system(topology, charge_from_molecules=[off_mol])`

but issue #1126 recommends using the forcefield, as charge_from_molecules may be deprecated soon.

**Comment by mattwthompson** [comment]
Hi @arepstein, thanks for the feedback and reproducing example, which runs the same for me. You've set everything up right and unfortunately you're running into a known issue (slow SMARTS matching with library charges #971); running just that step

```
forcefield['LibraryCharges'].find_matches(topology)
```

(which would normally be called at some point inside of `.create_openmm_system`) causes my interpreter to hang.

This poor performance on medium-to-large molecules is actually why we're a bit cautious in deprecating and then removing the `charge_from_molecules` functionality; we don't want to remove/move functionality without providing an acceptable alternative. Right now  **`charge_from_molecules` is the recommended way to do this** by nature of it being the _only_ way. Sorry if my tone in the linked issue implied it was going to be dropped in a matter of weeks or months - "soon" in terms of core toolkit functionality can mean multiple years depending on how quickly the alternatives are developed. We don't have a concrete timeline for making this change, but rest assured it would go through a deprecation period (likely several months, if not a year or more) before being removed.

**Comment by j-wags** [comment]
Yes, I totally agree with @mattwthompson. I reproduced the issue and also got the hang. It's almost certainly because LibraryChargeHandler is trying to find every permutation of atom mappings, and there's a combinatorial number of those. I think we'll need a heuristic to short-circuit this combinatorial matching before we can deprecate the current operation of the `charge_from_molecules` kwarg. 

So I echo @mattwthompson's recommendation to continue using the `charge_from_molecules` kwarg in this case. We'll issue a deprecation warning for a while if we plan on taking that away. Apologies for the confusing communication on this topic.

Does that resolve your use case, @arepstein?

**Comment by arepstein** [comment]
Thank you both for the thorough explanations! Yes, I'll stuck with `charge_from_molecules` for now.
