### ISSUE TITLE
The requested file format (MOL2) is not available from any of the installed toolkits

### ISSUE THREAD

**Issue by mbatgh** [openforcefield/openff-toolkit#1345]
Hi,
In short I do:

from openff.toolkit.topology import Molecule
molecule = Molecule.from_file(sdf_filename)
molecule.compute_partial_charges_am1bcc()
molecule.to_file(mol2out_filename, file_format='mol2')

I get:

Traceback (most recent call last):
  File ".../sdf2json.py", line 55, in <module>
    molecule.to_file(mol2out_filename, file_format='mol2')
  File ".../miniconda3/lib/python3.9/site-packages/openff/toolkit/topology/molecule.py", line 4839, in to_file
    raise ValueError(
ValueError: The requested file format (MOL2) is not available from any of the installed toolkits (supported formats: {'The RDKit': ['SDF', 'MOL', 'SMI', 'PDB', 'TDT'], 'AmberTools': [], 'Built-in Toolkit': []})

just installed the latest version of openff-toolkit (0.10.6), but i got the same issue ...
in https://docs.openforcefield.org/projects/toolkit/en/stable/api/generated/openff.toolkit.topology.Molecule.html?highlight=mol2#openff.toolkit.topology.Molecule.to_file
it says: Note that not all toolkits support all formats
... do I need openeye here? is there another way to export mol2? why does rdkit have no mol2?

thanks!
Michael

**Comment by lilyminium** [comment]
Hi @mbatgh, as far as I'm aware RDKit only supports reading in from MOL2 files, and does not support writing out, due to ambiguities in the file format: https://sourceforge.net/p/rdkit/mailman/rdkit-discuss/thread/CAF9ThQvTi%2BYt3FyDNa1qtHiUAf%2BbHm%3DhsibcZEFur-W4yCCwXg%40mail.gmail.com/#msg35461337

If you are able to convert the initial file into a MOL2 format (e.g. with openbabel?), MDAnalysis can write it back out e.g. something like this (untested code):

```python
import MDAnalysis as mda
from openff.toolkit.topology import Molecule

u = mda.Universe("my_uncharged_file.mol2")
offmol = Molecule.from_rdkit(u.atoms.convert_to("RDKIT"))
offmol.assign_partial_charges("am1bcc")
unitless_charges = [charge._value for charge in offmol.partial_charges]
u.add_TopologyAttr("charges", unitless_charges)  # or u.atoms.charges = unitless_charges
u.atoms.write("my_charged_file.mol2")
```

MDA currently does not support writing out MOL2 files if the Universe was not created from a MOL2 file, for similar reasons to RDKit: https://userguide.mdanalysis.org/stable/formats/reference/mol2.html#mol2-format

**Comment by mbatgh** [comment]
thanks - the MDanalysis approach looks interesting - for now i'll just use sdf as suggested in your link - one can also directly read json files ... its just one more step in the pipeline i wanted to avoid - closing.
