### ISSUE TITLE
Provide a way to silence the toolkit warning

### ISSUE THREAD

**Issue by mark-cresset** [openforcefield/openff-toolkit#1425]
Every time I use the tookit I get a 4-line warning message telling me to install the OpenEye toolkit. Not everyone has access to this, and it ends up filling up logs unnecessarily and hiding real warning messages. Would it be possible to 

a) remove this, or
b) touch a config file so that the message is only shown once per user, or 
c) put it under control of an environment variable, so that people who don't have/want the OE toolkit can turn the message off?

**Comment by mattwthompson** [comment]
Hi Mark,

I agree that warning is noiser than we'd wish. I also think it can come across with a different tone than was intended. We've been thinking about a solution described below, which is a slightly modified version of just removing it as long as you don't have them installed. (I can't imagine why you'd install them without a license, since they won't work, but we have frequent issues with users installing them but not wiring up the license file which can have undesired consequences.)

1. If OpenEye Toolkits are not installed, there is no warning emitted via top-level imports
2. If OpenEye Toolkits are installed and properly licensed, there is no warning emitted via top-level imports
2. If OpenEye Toolkits are installed and NOT properly licensed, there is a particular warning emitted, similar to the one that is currently emitted in case (1)

I anticipate (1) alone would be an improvement for you?

**Comment by mark-cresset** [comment]
This sounds ideal - thanks Matt!

**Comment by mattwthompson** [comment]
Look for this in the next release - probably version 0.11.2, unknown date.
