### ISSUE TITLE
Jupyter kernel crashes when making interchange

### ISSUE THREAD

**Issue by nathanmlim** [openforcefield/openff-toolkit#1553]
Hitting another issue with the toolkit_showcase example.

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/11985776/220423833-05ed1edb-5959-4333-bd88-e2b13ac346e1.png">

When assembling the forcefield with openff 2.0 + ff14sb 0.0.3 and I try to create the Interchange, my jupyter kernel just crashes. I've tried openff 1.3.1 + ffb14sb 0.0.3 to the same result. What is the recommended forcefields here?

**Comment by j-wags** [comment]
Woah, interesting. This is passing in our examples CI but I'm also seeing it get hung up on the interchange/openmm system-creation step in Binder. Thanks for bringing this to our attention @nathanmlim - I'll look into this!

**Comment by j-wags** [comment]
Ah, actually the binder is working fine, I just needed to let it run a bit longer. Let me try this locally...

**Comment by j-wags** [comment]
Ahhh, thanks for following up on that! OpenEye provides us a fully-featured license for our testing, but we have trouble covering cases of partially-featured licenses (since we don't have a partially-featured license to detect these cases). I've heard about this from other industry users as well, we could do better error reporting in this case.
