### ISSUE TITLE
isIsomorphic function behaves oddly

### ISSUE THREAD

**Issue by steinbt2** [openforcefield/openff-toolkit#1607]
I tested the isomorphic function on a simple molecule and found that while it is isomorphic to itself (duh...) I do not get the atom correspondence printed if I copy the molecule by converting it to smiles first. This does not match the API description where the function should return the atom pairs whenever two molecules are isomorphic. I attached a notebook showing the example. Note that this does not happen for all molecules, there is a simpler smiles String in the notebook that does not show this issue. 

**To Reproduce**
[IsomorphicOddity.zip](https://github.com/openforcefield/openff-toolkit/files/11427996/IsomorphicOddity.zip)
[condalist.txt](https://github.com/openforcefield/openff-toolkit/files/11428035/condalist.txt)

**Computing environment (please complete the following information):**
RHEL - Operating system, conda list output attached

**Comment by mattwthompson** [comment]
> This does not match the API description where the function should return the atom pairs whenever two molecules are isomorphic.

I don't think this is the case; the default behavior is for an atom map to not be returned whether or not the molecules are isomorphic (`return_atom_map=False`).

But in any case, you'd identified a very subtle corner case that's slipped through the cracks and was fun to track down. Since your three objects are isomorphic, you shouldn't be getting different results like you're seeing. Specifically, `print(Molecule.are_isomorphic(mol,mol3))` should return `True, None`. Gory details below the line.

---

The isomorphism checks have several short-circuits and one of them accidentally does not properly handle the `return_atom_map` argument. You happen to stumble across this trigger by round-tripping through SMILES, a conversion that happens to change the atom ordering since the SMILES pattern is not mapped.

```python
In [4]: [atom.atomic_number for atom in Molecule.from_smiles(SMILES).atoms]
Out[4]: [6, 7, 6, 6, 6, 6, 6, 8, 6, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [5]: [
   ...:     atom.atomic_number
   ...:     for atom in Molecule.from_smiles(
   ...:         Molecule.from_smiles(SMILES).to_smiles(explicit_hydrogens=False)
   ...:     ).atoms
   ...: ]
Out[5]: [6, 6, 8, 6, 6, 6, 6, 6, 7, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
```

This behavior is not consistent across all SMILES patterns (or wrapped toolkit versions, etc.) as you could tell with the other one you included. This is just a consequence of SMILES round-tripping:

```python
In [6]: Molecule.from_smiles("c1ccccc1").to_smiles(explicit_hydrogens=False)
Out[6]: 'c1ccccc1'
```

This short-circuit is implemented in in the private method `Molecule._is_exactly_the_same_as()`, which has stricter checks than isomorphism (atom order, etc.).

```python
In [3]: Molecule.from_smiles(SMILES)._is_exactly_the_same_as(Molecule.from_smiles(SMILES))
Out[3]: True

In [4]: Molecule.from_smiles(SMILES)._is_exactly_the_same_as(
   ...:     Molecule.from_smiles(ISOMORPHIC_SMILES)
   ...: )
Out[4]: False

In [5]: Molecule.from_smiles(SMILES).is_isomorphic_with(Molecule.from_smiles(ISOMORPHIC_SMILES))
Out[5]: True
```

**Comment by steinbt2** [comment]
Happy to provide some entertainment :-) You are right, I misread the documentation, 'None' should be the expected return in my example, not the atom map, unless explicitly requested.
