### ISSUE TITLE
Bring test_chemicalenvironments back online

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#200]

**Comment by j-wags** [comment]
Update -- @andrrizzi, @bannanc, and myself spoke about this last week. We realized that `environments.py` is essentially duplicated from Chemper, and the only functionality from it that we use is SMIRKS validation. We're going to keep that validation code around, but deprecate the rest of the functionality.

**Comment by bannanc** [comment]
I wanted to make sure the history on this was correct because this file doesn't come FROM chemper. It was created for the smarty/smirky algorithm back when everything was in the smarty github repo including the openforcefield toolkit. So it has ALWAYS been a part of the openforcefield tools. 

ChemPer has always supported both OE and RDK and I didn't want to make `openforcefield` a dependency in ChemPer until it also supported OE and RDK so I temporarily copied the file over there. Now that `openforcefield supports both toolkits I should be able to remove the chemper copy of `environment.py` and just make `openforcefield` a dependency.

**Comment by bannanc** [comment]
@j-wags I wanted to make sure you saw ^

**Comment by j-wags** [comment]
Recap of discussion between @bannanc and myself today:

`environment.py` is only used for validating SMIRKS currently. It is largely a duplicate of a core functionality in chemper. Do we actually need to maintain a duplicate copy of this in the Open Force Field toolkit?

Validating SMIRKS consists of three major steps:
1) Ensure that the SMIRKS is valid (that is, not gibberish)
2) Ensure that the SMIRKS contains the right number of tagged atoms for the parameter being described (eg. bond = 2 atoms, angle = 3 atoms...)
3) Ensure that the atoms in the SMIRKS are connected in the predicted way.

We both agree that 1) and 2) are essential to avoid scientific errors. 3) might actually not be necessary -- People may want to define weird non-explicit-valence parameters (perhaps a bond between things like water model H's, or an improper around a metal coordination site?)

Anyway, it's actually not too difficult to replace all of these with minimal calls For each point above: 
1) Code to check for gibberish in both OE and RDK [can be found here](https://github.com/openforcefield/openforcefield/blob/master/openforcefield/typing/chemistry/environment.py#L586-L619)
2) We can check this after each match, by counting the number of tagged atoms that were found
3) This may not be necessary, but we can check this after each match with a series of `TopologyAtom.is_bonded()` calls

Thus, I think we can plan to remove `environment.py` in a future milestone. This isn't critical (and will be a good opportunity to implement several tests), but we should get to it eventually to clean up the API and keep from confusing users.

**Comment by mattwthompson** [comment]
Since we are moving away from validating SMIRKS while loading force fields (#1472  #1509) and there has been no movement on this in almost four years, I do not think we are likely to do this.

Note of course that removing the code from a future release does not remove it from history or prevent it from being added back in the future.
