### ISSUE TITLE
Pin protein and water forcefield in our examples

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#284]
At the January meeting, [there seemed to be consensus](https://docs.google.com/presentation/d/1R2zM1bTqqDHUC534UKdI8vbdov2peNrQ3lA5-wtX_bc/edit#slide=id.g4d411744a8_0_0) that we would "pin" our small molecule forcefield to proteins parameterized using [AMBER ff14-sb](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/data/amber14/protein.ff14SB.xml) and water using [TIP3P-FB](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/data/tip3pfb.xml). 

We should switch over our examples to use these protein+water FF's, so that our userbase builds some familiarity with them. This could prevent incorrect usage of our forcefields down the line.

**Comment by davidlmobley** [comment]
Yes. We also want to make sure we have TIP3P-FB available in SMIRNOFF format! :)

**Comment by mattwthompson** [comment]
I'm going to close this, as it seems to be partially a scientific question and somewhat a remnant of the past era in which we were using OpenMM's force fields instead of our (mostly-functional-but-not-quite-perfect) [ff14SB port](https://github.com/openforcefield/openff-amber-ff-ports#installation). I'm also not quite sure what "pinning" means in this context - maybe just the selection of protein force field and water model used in our examples?

**If we want to distribute TIP3P-FB** as part of the toolkit or some package of ours, we can do that! Just let me know; I expect it to be a small task as long as my memory that it's the same sort of model as TIP3P but with different parameters.

**Comment by davidlmobley** [comment]
I agree, at this point we're firmly in the TIP3P camp and this issue should be closed.
