### ISSUE TITLE
Ensure that improper dihedrals are correctly interpreted by ParmEd

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#303]
(Initial issue post -- Requires cleanup) 

Per discussion between @j-wags @slochower

Of interest to @davidlmobley @jchodera 

References https://github.com/nhenriksen/speakeasy/blob/8a4a057a2797e7b2eb8be0c45724efcfdef2b01b/test/Benzene.ipynb

We are suspicious that, in using the Open Force Field toolkit to create an OpenMM system, and then using ParmEd to convert that to a AMBER system,  impropers may be getting lost or ignored by AMBER. The [PRMTOP written out by this process is here,](https://github.com/nhenriksen/speakeasy/commit/8a4a057a2797e7b2eb8be0c45724efcfdef2b01b#diff-47ddd3aaa07cbdd7663357cea4885fabR57) and only shows 23 dihedrals (when there should be 24? Maybe separate issue?) But importantly, there should also be 18 impropers, which aren't present

This issue needs verification and cleanup.

**Comment by j-wags** [comment]
Important note: Populating the ParmEd system's improper attribute is not the desired behavior, since that refers to CHARMM's improper format which is quadratic (?)
https://github.com/ParmEd/ParmEd/issues/990#issuecomment-397844139

**Comment by slochower** [comment]
> Important note: Populating the ParmEd system's improper attribute is not the desired behavior, since that refers to CHARMM's improper format which is quadratic (?)

My understanding, after talking about it briefly with Chaya, is that the statement `ProperTorsions potential="charmm"` in the SMIRNOFF specification is potentially misleading. In theory, CHARMM allows both harmonic-style and Fourier-style dihedral terms. If the periodicity is zero, then the potential is quadratic (i.e., harmonic). It's been a long time since I've done simulations in CHARMM, but in practice, I think the periodicity is almost always set to zero and therefore the potential is harmonic. See: https://github.com/ChayaSt/Charmm36_FF/blob/master/toppar/par_all36_cgenff.prm#L6257 The line is misleading -- to me, at least -- because it suggests that the torsions in SMIRNOFF99Frosst will be harmonic. But SMIRNOFF99Frosst has periodicities (i.e., multiplicities) that are not all zero, and they are modeled as cosines, just like in AMBER.

This lies at the root of the problem, I believe. For reasons that are unclear to me until I go through the ParmEd source, ParmEd is able to correctly interpret harmonic-style dihedrals as impropers. But ParmEd does not correctly separate Fourier-style dihedrals and impropers. I think they are are all lumped into `PeriodicTorsionForce` which all get written to the `DIHEDRAL` section in the `.frcmod` and do not get the correct negative sign applied to the fourth atom in the `.prmtop`. The thing is -- I'm not sure if anything is going wrong at the moment. Energies might be okay (I haven't had a chance to fully test). But the way that I see it, at best we are relying on undefined behavior with `tleap` reading an improperly formatted `.frcmod` and `pmemd` reading an improperly formatted `.prmtop`. @nhenriksen may be able to also fill in some details.

**Comment by davidlmobley** [comment]
I am confused about how a `.frcmod` file gets involved here. In my view the priority is to ensure we end up with correct `.prmtop` files (which it sounds like we're also having trouble with!) but `.frcmod` files are a whole other can of worms.

**Comment by slochower** [comment]
> I am confused about how a .frcmod file gets involved here. 

To add historical context to this and #304 and #302: these are issues I uncovered while working on `speakeasy`, where I was specifically exporting `.frcmod` and `.prmtop` files and checking them against ones written by pure AmberTools (where I knew there would be very slight differences in parameters applied to benzene by GAFF, but there should be the same number of torsions and impropers). So, that's why these issues all reference `.frcmod` files. The mishandling of impropers is what has been preventing `speakeasy` from working.

**Comment by davidlmobley** [comment]
OK. So this is in the context of *applying parameters to specific systems*. I think it's important to be clear on that, as that IS something potentially achievable, whereas exporting our whole forcefield to a frcmod file is not feasible.

**Comment by j-wags** [comment]
> My understanding, after talking about it briefly with Chaya, is that the statement ImproperTorsions potential="charmm" in the SMIRNOFF specification is potentially misleading. In theory, CHARMM allows both harmonic-style and Fourier-style improper terms.

Ah, this is a really good time to have caught this. I'm updating the SMIRNOFF spec right now, so I can change this to `potential-"fourier"` ad defaults for `ProperTorsions` and `ImproperTorsions`. Does this sound reasonable @jchodera @davidlmobley ?

**Comment by davidlmobley** [comment]
Yes!
