### ISSUE TITLE
Change name of BondType to BondParameter, AngleType to AngleParameter, etc

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#350]
@slochower and @SimonBoothroyd pointed out that, even after reading the class documentation, the names of the `ParameterType`-descended classes are confusing. They proposed, and I agree, that we should rename them to things like `BondParameter` and `AngleParameter`.

**Comment by andrrizzi** [comment]
I've changed this to priority high because we want to make all the API-breaking changes as early as possible.

**Comment by mattwthompson** [comment]
I share the same preference for `BondParameter`, but the toolkit is now stable enough we are not permitted to make improvements like this at the cost of breaking the API. And I'm not sure this change is necessarily worth the associated confusion/migration if we wanted to slip it into another API-breaking release.

Since no action has been taken on this, I'm going to close this issue. If we _do_ want to make this change, please re-open and we can discuss plans on how to execute this!
