### ISSUE TITLE
Reasonable-looking cyclohexane SMILES produces nonzero net charge

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#389]
**Describe the bug**

_Bug reported by @aniketsh_

**Note:** We are unable to reproduce this error in a new conda environment with just the OFF toolkit. Looking into the user's environment, it appeared that they made heavy use of [BioSimSpace](https://github.com/michellab/BioSimSpace) If we can reproduce this later and the root cause is incompatibility between toolkits, it may be worth opening a dialog with them to develop guidelines for users of both packages. See notes in Computing Environment section below

This process attempts to calculate charges for cyclohexane using a valid SMILES. Under the user's specific environment, this yielded charges close to the values below, but which added up to a roughly +0.5 net charge. I am unable to reproduce the error, but wanted to record this in case someone else gets the same result and we can capture it. 

```
from openforcefield.topology import Molecule
from openforcefield.utils.toolkits import AmberToolsToolkitWrapper, RDKitToolkitWrapper, ToolkitRegistry
tr = ToolkitRegistry(toolkit_precedence=[AmberToolsToolkitWrapper, RDKitToolkitWrapper])
smiles = '[H]C1([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C1([H])[H]'
mol = Molecule.from_smiles(smiles, toolkit_registry=tr)
mol.generate_conformers(toolkit_registry=tr)
mol.compute_partial_charges_am1bcc(toolkit_registry=tr)
print(mol.partial_charges)
from simtk import unit
tot = 0 * unit.elementary_charge
for pc in mol.partial_charges:
    tot += pc
print("Total charge on molecule", tot)
```

> [ 0.0377   -0.074733  0.0377   -0.074733  0.0377    0.0377   -0.074733
>   0.0377    0.0377   -0.074733  0.0377    0.0377   -0.074733  0.0377
>   0.0377   -0.074733  0.0377    0.0377  ] e
> Total charge on molecule 0.0040020000000000056 e

**Note again:* This is not a reproduction of the error. The user experienced a case where this code yielded a total charge was +0.5.

**Computing environment (please complete the following information):**
 - OSX
- *Environment which experienced the error was not conda*. 
- Other major infrastructure on the user's computer is [BioSimSpace](https://github.com/michellab/BioSimSpace). This seems like a high quality open-source package so it may be worth communicating with them about how we could provide user guidelines regarding interoperability/consistent environments with the OFF toolkit. If we end up being able to reproduce this behavior and find it's due to toolkit incompatibility, let's reach out. Pinging @lohedges and @chryswoods as a heads up, and maybe a friendly introduction. You're doing some very cool work :-)

**Comment by lohedges** [comment]
Hi @j-wags, thanks for the heads up. A core objective of the BioSImSpace project is interoperability, so if we're causing incompatibility issues with other toolkits in the field then it is certainly something that we'd like to fix. Due to the difficulty in producing a reliable Conda environment, I've primarily used and tested BioSimSpace in its own clean environment. We also require specific packages from other channels, e.g. RDKit, so the channel priority order during installation is crucial.

You are also doing great work, which we would certainly like to incorporate into BioSimSpace in the future.

Cheers.

**Comment by j-wags** [comment]
Thanks @lohedges. We'll stay in touch as we hear from more researchers that use both toolkits -- I'm excited to provide a great experience for users of OSS in comp chem. 

If you'd like, we can get you on the Open Force Field Slack to facilitate direct communication. I'd be happy to join into your communications channel as well. Though a part of me says it could be in the public interest to communicate publicly on GitHub.

**Comment by davidlmobley** [comment]
That sounds... peculiar. I've seen small noninteger formal charges before, but never anything significantly far from zero.

If they're using RDKit, they'd be getting partial charges from AmberTools, and I've used those a lot for charging and they tend to either fail entirely or generate reasonable charges. So this puzzles me greatly.

**Comment by lohedges** [comment]
> If you'd like, we can get you on the Open Force Field Slack to facilitate direct communication. I'd be happy to join into your communications channel as well. Though a part of me says it could be in the public interest to communicate publicly on GitHub.

Given the news on the Slack security breach, perhaps discussions there would be public too :-) Personally, unless there's a good reason to discuss things privately, I prefer to use GitHub issues. It's easier to keep track of things and to cross reference with the code / commits and whatnot. We also don't have paid Slack plan so interesting communication can get lost to the sands of time.

BioSimSpace makes use of the maximum common substructure functionality from RDKit. We need to use the package from the [rdkit](https://anaconda.org/rdkit/rdkit) conda channel because it uses a Boost Python library that doesn't conflict with the version that [Sire](https://github.com/michellab/Sire) was compiled against. (BioSimSpace is built on top of Sire.) The version of RDKit from conda-forge breaks things for us.

Yes, the formal charge issue is peculiar. We have our own built in method of estimating the net formal charge, based on code from [FESetup](https://github.com/CCPBioSim/fesetup). This uses the [Open Babel](http://openbabel.org/wiki/Main_Page) toolkit for the calculation. We don't have support for SMILES strings, but can start from a cyclohexane PDB file. We can also easily parameterise with AmberTools. (The following assumes your working in the `demo` diretory of the [BioSimSpace repository](https://github.com/michellab/BioSimSpace).)

```python
import BioSimSpace as BSS

# Load the cyclohexane PDB into a system and extract the only molecule.
m = BSS.IO.readMolecules("molecules/cyclohexane.pdb").getMolecules()[0]

# Compute and print the formal charge.
print(BSS.Parameters.formalCharge(m))
0.0000e+00 |e|

# Parameterise with GAFF and print the charge on the molecule.
mm = BSS.Parameters.gaff(m).getMolecule()
print(mm.charge())
5.5511e-17 |e|

# Parameterise with GAFF2 and print the charge on the molecule.
mm = BSS.Parameters.gaff2(m).getMolecule()
print(mm.charge())
5.5511e-17 |e|
```

Using RDKit directly gives a formal charge of zero also:

```python
from rdkit import Chem

smiles = "[H]C1([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C1([H])[H]"
m = Chem.MolFromSmiles(smiles)
print(Chem.rdmolops.GetFormalCharge(m))
0
```

**Comment by jchodera** [comment]
> We need to use the package from the rdkit conda channel because it uses a Boost Python library that doesn't conflict with the version that Sire was compiled against. (BioSimSpace is built on top of Sire.) The version of RDKit from conda-forge breaks things for us.

@lohedges : Out of curiosity, why did you compile sire against the `rdkit` channel instead of the `conda-forge` channel? We've run into some version incompatibility issues before as well.

Our ultimate goal is to migrate OpenMM and friends to `conda-forge` now that `cudatoolkit` packages are available there. Would be good to coordinate on that if you had the bandwidth and were also interested in migrating biosimspace there to solve channel incompatibility issues.

**Comment by lohedges** [comment]
Hi @jchodera!

> Out of curiosity, why did you compile sire against the rdkit channel instead of the conda-forge channel? We've run into some version incompatibility issues before as well.

Sorry, I don't think my comment was clear enough. Sire doesn't require RDKit, only BioSimSpace as one of its conda dependencies. Sire is built using [Boost](https://anaconda.org/conda-forge/boost) from `conda-forge`. When building BioSimSpace on top of Sire, RDKit from the `conda-forge` channel pulls in a different version of Boost which breaks things. I've checked and the version _should_ be compatible, so I'm not sure what's going wrong. I don't know if it's RDKit itself, or one if its dependencies that's causing the problem. The RDKit package in the `rdkit` channel instead pulls in (I think, off the top of my head) the [py-boost](https://anaconda.org/anaconda/py-boost) package, which can be installed alongside our existing Boost without messing things up.

> Our ultimate goal is to migrate OpenMM and friends to conda-forge now that cudatoolkit packages are available there. Would be good to coordinate on that if you had the bandwidth and were also interested in migrating biosimspace there to solve channel incompatibility issues.

Yes, I'd be really interested in hearing how your OpenMM migration goes. If successful, we should then be able to build Sire/BioSimSpace on `conda-forge` too. (Minus some third-party pip packages that would also need to be migrated.) This would hopefully solve a lot of the compatibility issues, and potentially open up Sire/BioSimSpace to a wider audience. (Where installation from non-approved Conda channels isn't allowed.) I imagine that we'll still keep our own channel active for frequent development builds.

**Comment by lohedges** [comment]
Just to say that having updated the version of Miniconda and conda-build used for Sire, I'm now able to use the RDKit package from `conda-forge` without issue. (It is built against Boost 1.7.0, which is the same as Sire.) It would be good to see if this resolves the original issue of @aniketsh.

Note that I can't install RDKit using Conda 4.7. Something has changed in their environment solving algorithm and, instead of the latest package, it installs version 2018.3.0 into our Sire Miniconda. (This version has Boost unpinned in its meta.yaml, but is actually built against Boost 1.68, so breaks our install.) Literally the only difference in the environment is the `conda` package, yet it resolves a different set of packages when you try installing RDKit.

**Comment by mattwthompson** [comment]
This seems to no longer be an issue (using 0.10.4):

```
>>> from openff.toolkit.topology import Molecule
>>> from openff.toolkit.utils import *
>>> import numpy as np
>>> molecule = Molecule.from_smiles('[H]C1([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C1([H])[H]')
>>> molecule.assign_partial_charges(partial_charge_method="am1bccelf10")
>>> np.sum(molecule.partial_charges)
Quantity(value=5.551115123125783e-17, unit=elementary charge)
>>> molecule.assign_partial_charges(partial_charge_method="am1bcc")
>>> np.sum(molecule.partial_charges)
Quantity(value=5.551115123125783e-17, unit=elementary charge)
>>> molecule.assign_partial_charges(partial_charge_method="am1bcc", toolkit_registry=ToolkitRegistry(toolkit_precedence=[RDKitToolkitWrapper(), AmberToolsToolkitWrapper()]))
>>> np.sum(molecule.partial_charges)
Quantity(value=0.0, unit=elementary charge)
```

`normalize_partial_charges=True` by default has happened since then, as has a handful of other changes to upstreams like RDKit, so it's hard to say how this was fixed. Please re-open or file another issue if something like this persists!
