### ISSUE TITLE
Fix docstrings for ParameterHandlers

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#397]
**Describe the bug**
Currently, the RTD pages for ParameterHandlers contain the docs for `ParameterAttribute`s, which are uninformative and misleading:
<img width="1268" alt="Screen Shot 2019-08-08 at 2 26 54 PM" src="https://user-images.githubusercontent.com/16329175/62739007-9e3f2380-b9e8-11e9-8dde-91eb4ad5f561.png">

**Comment by j-wags** [comment]
Bookmarking progress before I head to a meeting -- 

Fixing this probably requires changing a directive in [typing.rst](https://github.com/openforcefield/openforcefield/blob/master/docs/typing.rst)

It's probably a directive under autosummary: https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html

**Comment by jchodera** [comment]
It looks like this is because the [`See Also` section](https://github.com/openforcefield/openforcefield/blob/master/openforcefield/typing/engines/smirnoff/parameters.py#L155-L158) is interpreted as being part of the [`Parameters` section](https://github.com/openforcefield/openforcefield/blob/master/openforcefield/typing/engines/smirnoff/parameters.py#L142-L153) in interpreting the docstring.

The `See Also` section is a valid part of the [numpy docstring convention](https://numpydoc.readthedocs.io/en/latest/format.html) (section 12).
![image](https://user-images.githubusercontent.com/3656088/67731465-878be580-f9b5-11e9-8d86-54587370e786.png)

Perhaps this is a defect with the [`numpydoc` plugin](https://numpydoc.readthedocs.io/en/latest/)? It specifically says it supports [See Also](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard).
