### ISSUE TITLE
Make separate OpenForceFieldCore package

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#464]
**Is your feature request related to a problem? Please describe.**
There are several reasons that someone would want to use OFF Molecule/Topology/ToolkitWrapper objects without parameterizing anything at all. We should make a lightweight package that contains our core functionality that people could install independently of our heavyweight toolkit.

**Describe the solution you'd like**
We should make a separate installation route/conda package that contains only `Molecule`, `Topology, and `ToolkitWrapper`. This would let us consolidate stereochemistry checking code to a single place (instead of redundantly implementing it in both CMILES and OFFTK), and let us move Chemper away from re-implementing toolkit-wrapped mols.

**Comment by jchodera** [comment]
I'd suggest the conda package name might be `openforcefield-core`.

For reference, @jthorton pointed out how HTMD had just broken off https://github.com/Acellera/moleculekit, which was inspiration for this.

**Comment by jchodera** [comment]
Also, here is there [`Molecule`](https://github.com/Acellera/moleculekit/blob/master/moleculekit/molecule.py#L55) object.

**Comment by jaimergp** [comment]
Another project that provides APIs for Molecules and Biopolymers: [Autodesk Molecular Design Toolkit](https://autodesk.github.io/molecular-design-toolkit/api/molecule.html)

**Comment by mattwthompson** [comment]
This seems to have lost steam, though it could be picked up in the future. Since this issue was opened, the toolkit has actually gotten lighter by losing its OpenMM code to Interchange.

Note that on the packaging side of things, there is now `openff-toolkit-base` that provides the Python package and some of the more lightweight dependencies, whereas `openff-toolkit` brings in much more.
