### ISSUE TITLE
Make utility function to save PDB file from Topology

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openff-toolkit#502]
I was running a super short minimization/simulation and wanted to output a PDB of the OpenFF Topology to check that it had worked properly. However, we have a way to write a Molecule to a PDB easily but not a Topology. Doing it takes something like:
```
from simtk.openmm.app import PDBFile
openmm_topology = off_topology.to_openmm()
with open('output.pdb', 'w') as outfile:
    PDBFile.writeFile(openmm_topology, openmm_positions, outfile)
```
We should probably make a convenience function so this is easier/less confusing, e.g.:
`off_topology.save('myfile.pdb')`

**Comment by j-wags** [comment]
I propose the following:
* The function to save the PDB should be `Topology.to_file('myfile.pdb', positions)`, for consistency with `Molecule.to_file`

This Issue will be closed by a PR that:
*  Implements `Topology.to_file(file_path, positions, file_format="PDB")`, which:
    * Documents whether unitless `positions` are allowed, and what unit they would be assumed to be
    * Documents which distance unit the outputted PDB will use
    * Writes out a spec-conforming PDB with CONECT records
    * Raises a helpful Exception if the user requests an unsupported file format'
    * Raises a helpful Warning or Exception if VirtualSites are present in the `Topology`
* Implements tests that:
    * Ensures that unitless `positions` arguments are correctly handled (based on decision above)
    * Output a PDB and ensures that the number of ATOM lines and CONECT lines is appropriate
    * Ensure that writing a Topology with no atom names has sensible behavior
    * Ensure that the VirtualSite-handling behavior above is correctly implemented (based on decision above)
* Adds this function to at least one example notebook

**Comment by davidlmobley** [comment]
Sounds great. :)

**Comment by jchodera** [comment]
Do we want to ever consider having `Topology` carry around positions? Positions are optimal for `Molecule` objects, so it may make sense to also allow `Topology` to optionally carry positions---though I haven't though through this deeply yet.

**Comment by pavankum** [comment]
openmm outputs positions and topology to pdb by two calls:
PDBFile.writeModel()  -  that writes coordinates at every step
PDBFile.writeFooter()  -  that usually writes the topology at the end of simulation

A cheap workaround for openmm simulations is to create a copy of their pdbreporter.py and include the writeFooter() call after every call to PDBFile.writeModel(). Here is the file, https://github.com/openmm/openmm/blob/f9106ddb6a0d72c960c73b23ed0e07cd7190a80f/wrappers/python/simtk/openmm/app/pdbreporter.py, just adding writeFooter() after line 99 would output the topology at each step. 
And instead of openmm.app.PDBReporter() we can append something like Topology.off_pdbreporter(), the customized pdbreporter, to the call simulation.reporters.append() and it works fine.

**Comment by pavankum** [comment]
Reason for deleting comment: I might be going in a tangential direction, will toss the idea with @j-wags first.

**Comment by mattwthompson** [comment]
#724
