### ISSUE TITLE
Provide alternate sets of monovalent ion parameters

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openff-toolkit#54]
As discussed in #53, the AMBER force fields provide three recommended sets of ion parameters PER WATER MODEL. As proposed here (https://github.com/open-forcefield-group/openforcefield/pull/53#issuecomment-320097516) we need to make these different sets available in FFXML format.

I've added one set in #53 as a default set, but we need the full range to be available. SMIRKS patterns can be pulled from the FFXML file added there. We probably want to make an automatic utility script that can convert frcmod files for AMBER ion parameters sets into ffxml files for the next time someone decides to invent new set(s) of AMBER ion parameters. We can do this by coding equivalences between the relevant strings (e.g. `Li+`) and SMIRKS patterns.

**Comment by jchodera** [comment]
I imagine we should provide solvent and ion parameters in a different repository, rather than in the toolkit repository (which should only contain test files) or the http://github.com/openforcefield/smirnoff99Frosst repository (which contains our SMIRNOFF version of parm@Frosst). 

Perhaps we should create another repository for transliterations of AMBER force fields? We could call it `amber-smirnoff`.

**Comment by mattwthompson** [comment]
This doesn't seem like something that can be resolved with code changes to the toolkit. If this is still desired, we should transfer it to https://github.com/openforcefield/openff-forcefields
