### ISSUE TITLE
Molecule.from_rdkit() allows input of implicit-hydrogen molecules

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-toolkit#566]
**Describe the bug**
The `Molecule.from_rdkit(rdmol)` method will allow implicit-hydrogen molecules to be imported without converting them to explicit-hydrogen molecules.

**To Reproduce**
```python
from rdkit import Chem
molOrig = Chem.MolFromSmiles("CCCCCCCCCC")
ofmol = Molecule.from_rdkit(molOrig)
print(ofmol.atoms)
from rdkit import Chem
molOrig = Chem.MolFromSmiles("CCCCCCCCCC")
ofmol = Molecule.from_rdkit(molOrig)
print(ofmol.atoms)
```
returns a molecule without explicit protons that works in our pipeline just fine, except will always fail to produce anything useful:
**Output**
```
[Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6)]
```

**Computing environment (please complete the following information):**
 - `osx`
 - `openforcefield==0.6.0` and `rdkit==2019.09.03`

**Additional Context**
cc: https://github.com/openmm/openmmforcefields/issues/107

Remedies are either
* throw an exception on import
* add hydrogens explicitly
* don't worry about anything until `Molecule._validate()` is called just before we need a valid molecule (most permissive, hardest to debug issues)

**Comment by j-wags** [comment]
Agreed, thanks for pointing this out. I'm in favor of option 2, adding hydrogens explicitly.

I think that adding `Chem.AddHs` to `RDKitToolkitWrapper.from_rdkit` could solve this, though I'd want to look closely for unwanted side effects. If we find weird edge cases for some molecules, we could add a `hydrogens_are_explicit=True` argument (similar to what we have in `from_smiles`) to disable H addition unless it's requested. I was having a really weird time debugging #567, so that may be one such edge case.

**Comment by mattwthompson** [comment]
Related #144
