### ISSUE TITLE
Deprecate and remove dependence on openmoltools

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#609]
**Is your feature request related to a problem? Please describe.**
`openmoltools` is a collection of scattered tools used by the Chodera lab and others to do a variety of different tasks, packaged into a single "package" that is (and perhaps always will be) beta software. We should try to avoid hard dependence on beta software to reduce maintenance burden.

**Describe the solution you'd like**
1. Find what functionality exists in `openmoltools` that we need here (the list looks short: https://github.com/openforcefield/openforcefield/search?q=openmoltools&unscoped_q=openmoltools)
2. Deprecate and/or move functionality to here
3. Delete the dependency at some future date

**Comment by j-wags** [comment]
From a quick perusal of the search results: None of those invocations/imports are involved in core functionality, and many are just historical artifacts (scripts and notebooks) that still exist in the git tree. So there are no technical blockers to removing the functionality altogether. 

IMO This is more of an information curation/project history question -- Who will come looking for these functions in the future, where will they look, and how can we point them to a point in the git history where the functionality can be reproduced?

**Comment by davidlmobley** [comment]
FTR, it's sort of code that John and I began writing in the Dill lab in the mid-2000s that found its current home in `openmoltools` and accumulated a bunch of other things glued onto it.

We should probably also remove the deprecated examples which is probably MOST of what uses these.

I THINK most of them are there out of laziness -- that is, because they did handy things that otherwise required more calls to other toolkits like OpenEye or ParmEd, so it took us fewer lines of code (and code we knew) to just add a call to `openmoltools`. But we now have better ways of doing all of those things. So... I'm all in favor of just nuking them.

**Comment by mattwthompson** [comment]
The public API [and examples](https://github.com/conda-forge/openff-toolkit-feedstock/pull/9) no longer rely on `openmoltools` at all, so I'm going to call this complete.
