### ISSUE TITLE
Smirnoff+Amber simulation

### ISSUE THREAD

**Issue by aizvorski** [openforcefield/openff-toolkit#761]
I'm trying to follow the examples/using_smirnoff_with_amber_protein_forcefield/toluene_in_T4_lysozyme.ipynb .  Everything works, except there isn't any obvious way to take the resulting `complex_system` and run it in openmm.  

`complex_system` is an `openmm.System` which is produced from `complex_structure.createSystem` which is a ParmEd `Structure`.  To run an openmm simulation it's also necessary to have an openmm topology and positions.  The complex_structure contains position data since it can save a full structure with `complex_structure.save('file.pdb')`, but there is no obvious way to get those as openmm topology object.

How can I extend the toluene_in_T4_lysozyme example to actually running an openmm simulation?

**Comment by j-wags** [comment]
Hi @aizvorski ,

Thanks for writing in. This code should carry that example forward into a simulation (though, note that the minimization takes a while on my laptop):

```
from simtk import openmm, unit

# Propagate the System with Langevin dynamics.
time_step = 2*unit.femtoseconds  # simulation timestep
temperature = 300*unit.kelvin  # simulation temperature
friction = 1/unit.picosecond  # collision rate
integrator = openmm.LangevinIntegrator(temperature, friction, time_step)

# Length of the simulation.
num_steps = 1000  # number of integration steps to run

# Logging options.
trj_freq = 1  # number of steps per written trajectory frame
data_freq = 1  # number of steps per written simulation statistics

# Set up an OpenMM simulation.
simulation = openmm.app.Simulation(complex_structure.topology, complex_system, integrator)

# Set the initial positions.
positions = complex_structure.positions
simulation.context.setPositions(positions)

# Randomize the velocities from a Boltzmann distribution at a given temperature.
simulation.context.setVelocitiesToTemperature(temperature)

# Configure the information in the output files.
pdb_reporter = openmm.app.PDBReporter('trajectory.pdb', trj_freq)
state_data_reporter = openmm.app.StateDataReporter('data.csv', data_freq, step=True,
                                                   potentialEnergy=True, temperature=True,
                                                   density=True)
simulation.reporters.append(pdb_reporter)
simulation.reporters.append(state_data_reporter)

simulation.minimizeEnergy()
minimized_coords = simulation.context.getState(getPositions=True).getPositions()

simulation.context.setVelocitiesToTemperature(300*unit.kelvin)
simulation.step(10)
```

**Comment by aizvorski** [comment]
Thanks @j-wags !  This looks like it's working perfectly.  

Would you like me to add it to the example notebook?

**Comment by aizvorski** [comment]
P.S. One question: in this example the protein is already in water, but without water in the binding pocket.  If starting from a pdb file which has only the protein, what's the easiest way to add the ligand first and then a waterbox?

**Comment by j-wags** [comment]
Potentially an answer to both:

No need to add it to a notebook, I've just opened a PR with a [more extensive protein-ligand setup+simulation workflow](https://github.com/openforcefield/openforcefield/blob/ee506308c390a2fae3f1289652f47ad0717e9779/examples/toolkit_showcase/toolkit_showcase.ipynb). We'll probably iterate on that for a bit before the PR gets merged, but the code in that notebook should be a good starting point for what you're trying to do (though it requires mdtraj /`conda install -c conda-forge mdtraj`)

**Comment by aizvorski** [comment]
@j-wags Thank you very much!  Trying it now

**Comment by aizvorski** [comment]
@j-wags Thanks again - the example is very clear and worked out of the box for me.

A few questions / minor tweaks:
* Why is this bit needed?  `simulation.context.setPositions(pmd_complex_struct.positions + np.array([30, 30, 30])*unit.angstrom)`  It adds an offset to the positions, but what happens if they aren't offset?  (anything bad?)
* Is the recommended way to combine an Amber system and an OpenFF system with ParmEd?  `pmd_complex_struct = pmd_receptor_struct + pmd_ligand_struct` Is there a pure OpenMM equivalent?  (or is that basically too hard to do without ParmEd...)
* I changed to newest versions of the force fields, `ForceField('openff_unconstrained-1.3.0.offxml')` and `app.ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')`, if you'd like to update.  Not sure what 1.3 vs 1.2 does, but amber14 seems much better than 99.

**Comment by aizvorski** [comment]
Oh, just thought of one more question actually: can modeller add waters to a combination system which already has the combined protein and ligand?

**Comment by j-wags** [comment]
Ah, sorry, this must have gotten lost in my inbox! You may have already solved these by now, but here are some followups: 

> Why is this bit needed? simulation.context.setPositions(pmd_complex_struct.positions + np.array([30, 30, 30])*unit.angstrom) It adds an offset to the positions, but what happens if they aren't offset? (Is this something just to help the reporter or nglview?)

This is just something to help visualization. Otherwise the some visualization programs will have the protein start right on top of the periodic boundary and jump back and forth across the screen. 

> Is best way to combine an Amber system and an OpenFF system with ParmEd? pmd_complex_struct = pmd_receptor_struct + pmd_ligand_struct Is there a pure OpenMM equivalent? (or is that basically too hard to do without ParmEd...)

The two big pathways I've found are to either 1) make them separately and then combine them using ParmEd or 2) make them simultaneously using `openmmforcefields`. I'm not sure whether one is strictly better than the other, it will depend on a lot of specifics, and it may be best to try both. In the near future we hope to have OpenFF Interchange provide a replacement for ParmEd in this context!

> I changed to newest versions of the force fields, ForceField('openff_unconstrained-1.3.0.offxml') and app.ForceField('amber14-all.xml', 'amber14/tip3pfb.xml'), if you'd like to update. Not sure what 1.3 vs 1.2 does, but amber14 should be better than 99?

We've updated to `openff-2.0.0` since this was posted. I can't recall the reasoning for using `amber99`, but `amber14` would almost certainly be better. I'd be happy to take a PR for this (cc @Yoshanuikabundi)

> Oh, just thought of one more question actually: can modeller add waters to a combination system which already has the combined protein and ligand?

Modeller can't do this, since it needs ligand parameters (probably just vdW radii to help know when a water's clashing). But I think that [PDBFixer](https://htmlpreview.github.io/?https://github.com/openmm/pdbfixer/blob/master/Manual.html) can do it - I talked with someone a bit about this in December but unfortunately don't have the code at hand. 

Again, apologies for the late replies! Please let me know if you have other questions. I'll close this issue for now since we're doing a bit of a cleanup but feel free to reopen it or start a new issue for further questions.

**Comment by metma99** [comment]
Hello:
I am trying to follow your example here: [https://github.com/openforcefield/openforcefield/blob/ee506308c390a2fae3f1289652f47ad0717e9779/examples/toolkit_showcase/toolkit_showcase.ipynb](url)
However, not with much luck. I assume there have been too many changes to the API since the notebook was created.
I am using RDKit 2022.09.01, AmberTools 22.0,, and OpenToolkit version 0.11.4.
Is there a possibility to update this example?
May thnaks in advance,
Markus

**Comment by mattwthompson** [comment]
Try using the most recent version of that notebook: https://github.com/openforcefield/openff-toolkit/blob/main/examples/toolkit_showcase/toolkit_showcase.ipynb

You can replace `main` in the URL with i.e. `0.11.4` or any other tag or commit to point it to a different branch, tag, release, commit, etc. You are using a version from a commit that is not associated with a release (or stable PR).

The versions of the other packages you list are up to date and will work with the most recent version of this notebook.

**Comment by mainguyenanhvu** [comment]
Hi @j-wags, which module do I need to import when using complex_structure.createSystem?

Thank you very much.

**Comment by j-wags** [comment]
Hi @mainguyenanhvu, 

In the future please don't comment on closed issues - just make a new issue for questions like this. It's hard to notice posts on closed issues, so you're less likely to get an answer and other folks are less likely to benefit from your question being answered :-) 

In this example, `complex_structure` was a ParmEd `Structure` object. You can see the example in it's 3-year old form [here](https://github.com/openforcefield/openff-toolkit/blob/0.7.0/examples/using_smirnoff_with_amber_protein_forcefield/toluene_in_T4_lysozyme.ipynb), though note that we no longer recommend that approach. Instead you can find a more recent example involving combining AMBER and OpenFF force fields [here](https://github.com/openforcefield/openff-toolkit/blob/0.14.3/examples/using_smirnoff_with_amber_protein_forcefield/BRD4_inhibitor_benchmark.ipynb).
