### ISSUE TITLE
Fix OpenMM<->AMBER round-trip parameter comparison notebook

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#778]
**Describe the bug**
`examples/using_smirnoff_in_amber_or_gromacs/convert_to_amber_gromacs.ipynb` fails when performing an OpenMM System --> AMBER prmtop --> OpenMM System round trip. This happens because ParmEd now separates the Electrostatic and vdW components into a `NonbondedForce` object with correct charges but all-0 sigmas, and a `CustomNonbondedForce` with tabulated lookups for pre-calculated vdW interaction parameters. 

https://github.com/openforcefield/openforcefield/pull/777/checks?check_run_id=1512345807#step:14:129

**To Reproduce**
Run the notebook above, or check test status

**Output**
In the following notebook cell:
```
from simtk import unit
from simtk.openmm.app import PME, HBonds
from openforcefield.tests.utils import compare_system_parameters, compare_system_energies

# Load the prmtop/inpcrd files into a ParmEd Structure.as an OpenMM System object.
amber_structure = parmed.load_file('system.prmtop', 'system.inpcrd')

# Convert the Structure to an OpenMM System. Note that by
# default ParmEd will add a CMMotionRemover force to the
# System, and won't constrain the hydrogen bonds.
amber_system = amber_structure.createSystem(nonbondedMethod=PME,
                                            nonbondedCutoff=9.0*unit.angstrom,
                                            switchDistance=0.0*unit.angstrom,
                                            constraints=HBonds,
                                            removeCMMotion=False)

# Compare the parameters of the original and converted Systems.
# This raises FailedParameterComparisonError if the comparison fails.
compare_system_parameters(omm_system, amber_system)

# Compare the energies by force.
# This raises FailedEnergyComparisonError if the comparison fails.
amber_energies, omm_energies = compare_system_energies(
    amber_system, omm_system, amber_structure.positions, amber_structure.box_vectors,
    rtol=1e-3)
```

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-7-ea35df2310cd> in <module>()
>      17 # Compare the parameters of the original and converted Systems.
>      18 # This raises FailedParameterComparisonError if the comparison fails.
> ---> 19 compare_system_parameters(omm_system, amber_system)
>      20 
>      21 # Compare the energies by force.
> 
> /Users/jeffreywagner/projects/OpenForceField/openforcefield/openforcefield/tests/utils.py in compare_system_parameters(system1, system2, systems_labels, ignore_charges, ignore_improper_folds)
>    1372     if set(force_names1) != set(force_names2):
>    1373         err_msg = "The two Systems have different forces to compare:\n - system1 {}\n - system2 {}"
> -> 1374         raise ValueError(err_msg.format(sorted(force_names1), sorted(force_names2)))
>    1375 
>    1376     # Find all the pair of forces to compare.
> 
> ValueError: The two Systems have different forces to compare:
>  - system1 ['HarmonicAngleForce', 'HarmonicBondForce', 'NonbondedForce', 'PeriodicTorsionForce']
>  - system2 ['CustomNonbondedForce', 'HarmonicAngleForce', 'HarmonicBondForce', 'NonbondedForce', 'PeriodicTorsionForce']

**Additional context**
I think the best place to fix this will be in[ `compare_system_parameters`, where we organize the parameters into dicts for comparison](https://github.com/openforcefield/openforcefield/blob/master/openforcefield/tests/utils.py#L1393-L1395). It'll be a little bit complicated because the new ParmEd representation has the interaction parameters pre-multiplied, but it should be possible to do a fair comparison with a bit of work.

**Comment by mattwthompson** [comment]
Tagging #777

**Comment by davidlmobley** [comment]
Do we still maintain `compare_system_parameters` or is it deprecated? If deprecated perhaps this is a "won't fix", otherwise we should try and update how we interact with ParmEd to make this behave correctly, I think...?

**Comment by mattwthompson** [comment]
> Do we still maintain `compare_system_parameters` or is it deprecated?

~~We could deprecate it; it's used in some unit tests but we've remade the same functionality in other places so it could be swapped out for something else.~~

> If deprecated perhaps this is a "won't fix", otherwise we should try and update how we interact with ParmEd to make this behave correctly, I think...?

~~It might be simpler to drop this functionality altogether~~

Actually, after some more digging, I'm going to close this - both because it's no longer an issue and because we're moving away from using it.

The band-aid fix originally was to just ignore this notebook in tests. But at some point in time, it stopped being ignored and it's been passing for a while now. Exactly when this happened has been lost to the sands of time and/or my limited patience digging through git history (it was un-ignonred, perhaps accidentally, in #911 and didn't throw errors). I checked the workflow files to be sure it's running, and a recent [log](https://github.com/openforcefield/openff-toolkit/runs/5045237355?check_suite_focus=true#step:11:129) from last night confirms that it's running and passing.

Additionally, the notebook containing the original issue is getting nudged out the door, i.e. #1113 updated this folder to have side-by-side notebooks using ParmEd and Interchannge.
