### ISSUE TITLE
Split Monolithic Files

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-toolkit#834]
**Is your feature request related to a problem? Please describe.**

There are several files in the project which are over 5000 lines long, including `toolkits.py` and `molecule.py`. Having such large files make a) IDEs which perform static code analysis run slowly when editing the files, especially in terms of code completion and linting, b) makes it hard to find what you're looking for without scrolling over 1000s of lines, c) makes it daunting for potential new contributors.

It would be good to split these up into smaller sub-files. The module imports can be retained by exposing classes in the split files via the root `__init__.py` of a module so as not to break the API.

**Describe the solution you'd like**

As a start, split the following would be a big plus:

```
- utils
    - toolkits
        - __init__.py         <- Expose all classes through here to not break API.
            | GLOBAL_TOOLKIT_REGISTRY
            | OPENEYE_AVAILABLE         <- Consider removing these as I'm not sure what they actually do?
            | RDKIT_AVAILABLE
            | AMBERTOOLS_AVAILABLE
            | BASIC_CHEMINFORMATICS_TOOLKITS  <- Remove the warning as it's never triggered?
        - exceptions.py         <- Maybe add a module for the general custom exceptions?
            | MissingPackageError         <- Delete as it is unused?
            | ToolkitUnavailableException
            | LicenseError
            | InvalidToolkitError
            | InvalidToolkitRegistryError
            | UndefinedStereochemistryError
            | ChargeMethodUnavailableError
            | IncorrectNumConformersError
            | IncorrectNumConformersWarning
            | ChargeCalculationError
            | InvalidIUPACNameError
        - toolkits.py
            | ToolkitWrapper
            | BuiltInToolkitWrapper
            | ToolkitRegistry
        - ambertools.py
            | GAFFAtomTypeWarning
            | AntechamberNotFoundError
        - rdkit.py
            | RDKitToolkitWrapper
        - openeye.py
            | OpenEyeToolkitWrapper
```

similar attention should likely be given to `molecule.py` and potentially `topology.py`.

**Comment by mattwthompson** [comment]
+1 from me in general, this more closes matches my style preferences. Two small benefits I would add are d) it makes it easier to move things around, like if we wanted to move `OpenEyeToolkitWrapper` out, and e) my browser struggles with some of GitHub's UI with these large files. The only downside that comes to mind is that the git history gets messier, but I think the tradeoff is worth it. This is all assuming no unforeseen API breaks.

**Comment by j-wags** [comment]
I like this plan. Happy to delete anything that's unused, and the refactor plans look mostly good. 

I think that the new filenames for toolkit wrappers should indicate that they're wrappers (eg `rdkit_toolkit_wrapper.py`), and that the built-in toolkit should have its own file.

For the `X_AVAILABLE` module-level vars, since they're in the public API, we should include a "migration note" of sorts in the releasenotes telling people how to replace it with a more functional command (probably `X.is_available()`). Also, since this will change the public API, we should plan these changes for a major release. 

Finally, I notice that we're inconsistent about how we import these modules in our own code. Sometimes we say `from openff.toolkit.utils.toolkits import RDKitToolkitWrapper` and other times `from openff.toolkit.utils import RDKitToolkitWrapper`. This will be API-breaking for the former case, and it may be good to audit the code, docstrings, and examples to ensure that we're pointing users to the "better practice" of using the shorter imports (putting this on the radar for @Yoshanuikabundi... maybe we can get to this in a few months!)

**Comment by mattwthompson** [comment]
It might be worth doing this for like `molecule.py` and `topology.py`, although those files include fewer classes than `toolkits.py` did
