### ISSUE TITLE
OpenEye tests are being skipped (inconsistently?)

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#937]
At some point in the past few days, OpenEye tests in the toolkit got turned off again. This causes a false green check, since the failing tests (#886) on the master branch are in the ~10,000 skipped tests. I was about to merge https://github.com/openforcefield/openff-toolkit/pull/917 before I realized that tests should be failing on the master branch and any PRs that don't fix #886.

* The past few hours, everything "passes" but with [thousands of failed tests. 
](https://github.com/openforcefield/openff-toolkit/runs/2582202053)
* Previously, there were a few (known) failures with [roughly 20 skipped tests](https://github.com/openforcefield/openff-toolkit/actions/runs/840628314).
* I've looked through more logs from the past few months than I can count and I can't find a pattern
* The most recent [commit](https://github.com/openforcefield/openff-toolkit/commit/1bb07cfa4ceffee4a1df760e44fdbdb1d281d1c7) to the master branch is squash-merging #916, which really shouldn't have had an impact on this. 
* The doc/examples PRs (#763, #934) were worked on and merged, but these should have no impact since they did not touch config files.
* The license check is passing ( has been passing, and I restarted it just now): https://github.com/openforcefield/status/actions/workflows/oe_license.yml
* A [check](https://github.com/openforcefield/openff-toolkit/blob/a0bcb3b1b763718d01ed0bdb0e359b766b302561/.github/workflows/CI.yml#L115-L136) I added in at some point in the past is meant to safeguard against this, but is not triggering a failure. It checks if 
* The same version of the toolkits seems to be pulled down each time (`openeye-toolkits          2020.2.2                 py37_0    openeye`)
* Nothing of note in recent [pytest](https://docs.pytest.org/en/6.2.x/changelog.html) changes.
* It looks like my [fix](https://github.com/openforcefield/openff-toolkit/pull/875#issuecomment-841404138) from a few weeks ago didn't work? That would not explain why the behavior has been flip-flopping since then ...

I am so very confused.

**Comment by j-wags** [comment]
Woah, this is strange. The new OE license is on a much shorter expieration cycle than the old one (because of the codecov leak). One remote possibility is that the CI machines are sometimes out of whack about the date? That would make some of them think their OE license is already expired.

**Comment by mattwthompson** [comment]
I think any licensing issue would cause a failure on this line: https://github.com/openforcefield/openff-toolkit/blob/a0bcb3b1b763718d01ed0bdb0e359b766b302561/.github/workflows/CI.yml#L119

**Comment by mattwthompson** [comment]
It's possible to capture, in memory, the test output before it gets logged. [S/O link](https://stackoverflow.com/a/54639164/4248961). A solution to this problem could potentially be to something like this to `conftest.py`:

```python3
def check_not_too_many_tests_skipped(terminalreporter, exitstatus, config):
    """Raises an exception if too many tests are skipped on runs with OpenEye installed"""
    # grab the `matrix.cfg.openeye` variable from the workflow, 
    # do NOT rely on OpenEyeToolkitWrapper.is_available
    is_openeye_run = ... 
    if "skipped" in terminalreporter.stats and is_openeye_run:
        num_skipped_tests = len(terminalreporter.stats["skipped"]))
            if num_skipped_tests > 100:  # pick a number, or make it an arg
            raise Exception(f"Too many skipped tests ({num_skipped_tests}) in OpenEye builds!")
```

This might also be useful for other projects (https://github.com/ParmEd/ParmEd/pull/1173)

**Comment by j-wags** [comment]
I like that idea in general, and I'm weighing it against the downside that it adds even more complexity to the tests. 

But we still don't have a root cause for the current spotty OE behavior, so I'd like to focus on that first.

**Comment by j-wags** [comment]
Even if we can't reproduce it, are we able to isolate this problem? I think this might fully explained if we see it as the combination of two factors:

1) The GBSA tests only run on the nightlies, since they specify `--runslow`. Something broke a few of them.
2) The OpenEye tests are sporadic, and we don't know the cause

Using [this example output with `--runslow`](https://github.com/openforcefield/openff-toolkit/actions/runs/843813829) and [this example output without it](https://github.com/openforcefield/openff-toolkit/actions/runs/835581543), I see the following numbers from mac tests:

| link                                                                                                          | RDKit | OpenEye | `--runslow` | failed | passed | skipped | xfailed | xpassed |
|---------------------------------------------------------------------------------------------------------------|-------|---------|-------------|--------|--------|---------|---------|---------|
| [source](https://github.com/openforcefield/openff-toolkit/runs/2566636433?check_suite_focus=true#step:12:506) | Y     | Y       | N           | 0      | 16385  | 9470    | 81      | 315     |
| [source](https://github.com/openforcefield/openff-toolkit/runs/2566636394?check_suite_focus=true#step:12:485) | N     | Y       | N           | 0      | 14440  | 10344   | 80      | 314     |
| [source](https://github.com/openforcefield/openff-toolkit/runs/2566636344?check_suite_focus=true#step:12:287) | Y     | N       | N           | 0      | 1710   | 9714    | 4       | 3       |
| [source](https://github.com/openforcefield/openff-toolkit/runs/2588244750?check_suite_focus=true#step:12:585) | Y     | Y       | Y           | 7      | 25822  | 26      | 81      | 315     |
| [source](https://github.com/openforcefield/openff-toolkit/runs/2588244739?check_suite_focus=true#step:12:586) | N     | Y       | Y           | 9      | 23859  | 916     | 80      | 314     |
| [source](https://github.com/openforcefield/openff-toolkit/runs/2588244727?check_suite_focus=true#step:12:287) | Y     | N       | Y           | 0      | 1715   | 9709    | 4       | 3       |

So, from these numbers, I see evidence of 1) from above, but I don't see evidence of 2). Can we find an instance of running the CI **with** OE where we get different numbers than the "OE=Yes" rows of this table?

**Comment by j-wags** [comment]
I've looked at several more logs from the past month, and can't find any that show an instance of case 2). I think it's possible that this is a cruel joke of fate, and that we're confusing `9470` (the number of skipped tests when everything goes right in the first row) with `9714` (the number of skipped tests when things go _wrong_ in the way we had been suspecting) and `9709` (the surprisingly high number of skipped tests when we do `--runslow` in RDKit-only builds license)
